// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"reflect"

	"github.com/geoffjay/pres/baml_client/stream_types"
	"github.com/geoffjay/pres/baml_client/types"
)

var typeMap = map[string]reflect.Type{
	"TYPES.Presentation":                   reflect.TypeOf(types.Presentation{}),
	"STREAM_TYPES.Presentation":            reflect.TypeOf(stream_types.Presentation{}),
	"TYPES.PresentationPreparation":        reflect.TypeOf(types.PresentationPreparation{}),
	"STREAM_TYPES.PresentationPreparation": reflect.TypeOf(stream_types.PresentationPreparation{}),
	"TYPES.PresentationQuestion":           reflect.TypeOf(types.PresentationQuestion{}),
	"STREAM_TYPES.PresentationQuestion":    reflect.TypeOf(stream_types.PresentationQuestion{}),
	"TYPES.PresentationUpdate":             reflect.TypeOf(types.PresentationUpdate{}),
	"STREAM_TYPES.PresentationUpdate":      reflect.TypeOf(stream_types.PresentationUpdate{}),
	"TYPES.Slide":                          reflect.TypeOf(types.Slide{}),
	"STREAM_TYPES.Slide":                   reflect.TypeOf(stream_types.Slide{}),
}
